configPath: src/sveltecms.config.yml
types:
  blog:
    slug:
      fields: date,title
      slugify: [removeTimestamp, slugify]
    fields:
      title: title
      date: date
      image: image
      body: body
contentStores: {}
mediaStores:
  images:
    type: staticFiles
    mediaDirectory: images
    allowMediaTypes: image/jpeg, image/png, image/gif
fields:
  body: markdown
  title: text
  image: image
widgets:
  date:
    type: date
    time: editable
  textarea:
    type: textarea
    autosize: true
    resize: vertical
_slug: sveltecms.config