// This file is auto-generated by SvelteCMS at /admin/components.
import content_BlogPost from "$lib/content/BlogPost.svelte";

export const components = [
  { id:'content_BlogPost', component:content_BlogPost }
]

export default components;