// This file is auto-generated by SvelteCMS at /admin/components.
import content_BlogPost from "$lib/content/BlogPost.svelte";
import element_Button from "$lib/element/Button.svelte";

export const components = [
  { id:'content_BlogPost', component:content_BlogPost },
  { id:'element_Button', component:element_Button }
]

export default components;