configPath: src/sveltecms.config.yml
settings:
  rootContentType: landingPage
  frontPageSlug: front
types:
  blog:
    slug: date,title
    fields:
      title: title
      date: date
      image: image
      body: body
    displayComponent: content_BlogPost
  landingPage:
    displayComponent: content_LandingPage
    fields:
      title:
        type: title
        display: false
      slug: slug
      blocks:
        type: fieldgroup
        multiple: true
        multipleLabelFields: _fieldgroup
        widget:
          type: fieldgroup
          options:
            fieldgroups: fullwidth
    contentStore:
      type: staticFiles
      fileExtension: json
    slug: slug
contentStores: {}
mediaStores:
  images:
    type: staticFiles
    mediaDirectory: images
    allowMediaTypes: image/jpeg, image/png, image/gif
  icons:
    type: staticFiles
    mediaDirectory: images/icons
    allowMediaTypes: image/png
fields:
  title:
    type: text
    required: true
    display: h1
  date:
    type: date
    required: true
  body: markdown
  slideText:
    type: markdown
    widget: slideText
  slug:
    type: text
    display: false
  h1:
    type: text
    display: h1
  image:
    type: image
    mediaStore: images
  style:
    type: text
    display: false
    helptext: |-
      This value will go within a style tag.
      Example: "top:5%; width:30%; text-align:center;"
  button:
    type: fieldgroup
    display: element_Button
    fields:
      href:
        type: text
        required: true
        helptext: If provided, the button will be rendered as a link that looks like a button.
      text:
        type: text
        required: true
        helptext: The text that appears inside the <button> or <link> element.
      helptext:
        type: text
        required: true
        helptext: Any help text that should be shown for screen readers or when hovering over the element.
widgets:
  date:
    type: date
    time: editable
  textarea:
    type: textarea
    rows: 15
    cols: 0
    autosize: false
  slideText:
    type: textarea
    rows: 5
    autosize: true
  imageOnly:
    type: image
    altField: false
fieldgroups:
  hero:
    type: fullwidth
    fields:
      image:
        type: image
        widget: imageOnly
      imageFilter: text
      heading:
        type: slideText
        widget:
          type: textarea
          rows: 2
      text: slideText
      textStyle: style
  frontslides:
    type: fullwidth
    fields:
      slides:
        type: fieldgroup
        multiple: true
        multipleLabelFields: heading
        fields:
          heading: text
          text: slideText
          icon:
            type: image
            mediaStore: icons
  quoteBlock:
    fields:
      quote: markdown
_slug: sveltecms.config