configPath: src/sveltecms.config.yml
settings:
  rootContentType: landingPage
  frontPageSlug: front
  defaultContentDisplay: div.prose.dark:prose-invert
contentTypes:
  blog:
    slug: date,title
    fields:
      title: title
      date: date
      image: image
      body: body
      tags: tags
    label: ''
  landingPage:
    display: content_LandingPage
    fields:
      title:
        type: title
        display: none
      slug: slug
      blocks:
        type: fieldgroup
        multiple: true
        multipleLabelFields: _fieldgroup
        widget:
          type: fieldgroup
          fieldgroupTypes: fullwidth
    contentStore:
      type: staticFiles
      fileExtension: json
    slug: slug
    label: ''
  docs:
    fields:
      title: title
      body: body
    slug: title
    label: ''
  tags:
    label: ''
    slug: title
    fields:
      title: title
      body: body
      taggedContent: taggedContent
contentStores: {}
mediaStores:
  images:
    type: staticFiles
    mediaDirectory: images
    allowMediaTypes: image/jpeg, image/png, image/gif
  icons:
    type: staticFiles
    mediaDirectory: images/icons
    allowMediaTypes: image/png
fields:
  title:
    type: text
    index: true
    required: true
    display:
      type: span
      link: true
    displayModes:
      teaser:
        type: h2
        link: true
      page: h1
  date:
    type: date
    index: true
    required: true
    default: $now
  body: markdown
  slideText:
    type: markdown
    widget: slideText
  slug:
    type: text
    display: none
  h1:
    type: text
    display: h1
  image:
    type: image
    index: true
    mediaStore: images
  style:
    type: text
    display: none
    helptext: |-
      This value will go within a style tag.
      Example: "top:5%; width:30%; text-align:center;"
  button:
    type: fieldgroup
    display: element_Button
    fields:
      href:
        type: text
        required: true
        helptext: >-
          If provided, the button will be rendered as a link that looks like a
          button.
      text:
        type: text
        required: true
        helptext: The text that appears inside the <button> or <link> element.
      helptext:
        type: text
        required: true
        helptext: >-
          Any help text that should be shown for screen readers or when hovering
          over the element.
  tags:
    type: reference
    widget:
      type: reference
      referenceKey: taggedContent
      contentTypes: tags
      freeTagging: true
  taggedContent:
    type: reference
    widget:
      type: reference
      referenceKey: tags
      displayMode: teaser
widgets:
  date:
    type: date
    time: editable
  textarea:
    type: textarea
    rows: 15
    cols: 0
    autosize: false
  slideText:
    type: textarea
    rows: 5
    autosize: true
  imageOnly:
    type: image
    altField: false
fieldgroups:
  hero:
    type: fullwidth
    fields:
      image:
        type: image
        widget: imageOnly
      imageFilter: text
      heading:
        type: slideText
        widget:
          type: textarea
          rows: 2
      text: slideText
      textStyle: style
  frontslides:
    type: fullwidth
    fields:
      slides:
        type: fieldgroup
        multiple: true
        multipleLabelFields: heading
        fields:
          heading: text
          text: slideText
          icon:
            type: image
            mediaStore: icons
  quoteBlock:
    fields:
      quote: markdown
_slug: sveltecms.config
_type: admin