configPath: src/sveltecms.config.yml
types:
  blog:
    slug: date,title
    fields:
      title: title
      date: date
      image: image
      body: body
contentStores:
  staticFiles:
    id: staticFiles
    contentDirectory: content
    prependContentTypeIdAs: directory
    fileExtension: md
    markdownBodyField: body
mediaStores:
  images:
    type: staticFiles
    mediaDirectory: images
    allowMediaTypes: image/jpeg, image/png, image/gif
fields:
  body: markdown
  date:
    type: date
    preSave: toString
    preMount: date
  title: text
  image: image
_slug: sveltecms.config